name: Deploy FastAPI app to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENT }}" > backend/.env

    - name: Create firebase config file
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" > backend/iot-patient-monitoring-s-8a328-firebase-adminsdk-w8gnl-e08f5c2d89.json

    - name: Create PEM file
      run: |
        echo "${{ secrets.PEM_FILE_CONTENT }}" > backend/private-subnet-patient-management.pem

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PEM_FILE_CONTENT }}

    - name: Create temporary directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 'mkdir -p /home/ubuntu/temp'

    - name: Copy configuration files to EC2
      run: |
        scp -o StrictHostKeyChecking=no \
          backend/.env \
          backend/iot-patient-monitoring-s-8a328-firebase-adminsdk-w8gnl-e08f5c2d89.json \
          backend/private-subnet-patient-management.pem \
          ubuntu@${{ secrets.SSH_HOST }}:/home/ubuntu/temp/

    - name: Pull latest changes on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} '
            cd /home/ubuntu/Smart-IoT-Patient-Monitoring-System &&
            git pull origin main
        '

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 'bash -s' < backend/deploy.sh

    - name: Clean up temporary files
      if: always()
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} '
          rm -rf /home/ubuntu/temp
          rm -f ~/.git-credentials
        '