name: Deploy to EC2 🚀

on:
  push:
    branches:
      - "main" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch ✅
        uses: actions/checkout@v2

      - name: Set up SSH key and whitelist EC2 IP address 🐻‍❄️
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Create .env file dynamically 🧨
        env:
          ENV: ${{ secrets.ENV_CONTENT }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "ENV=${ENV}" >> env
          echo "SSH_USER=${SSH_USER}" >> env
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> env

      - name: Copy files to remote server 🚙
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          scp -r * $SSH_USER@$SSH_HOST:/home/ubuntu/

      - name: Run Bash Script To Delpoy App 🚀
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "chmod +x ./backend/deploy.sh && ./backend/deploy.sh"

      - name: Clean up SSH key 🚀
        if: always()
        run: rm -f ~/.ssh/id_rsa