name: Deploy FastAPI app to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create temporary directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 'mkdir -p /home/ubuntu/temp'

    - name: Copy configuration files to EC2
      run: |
        scp -o StrictHostKeyChecking=no \
          backend/.env \
          backend/secret.pem.firebase.json \
          backend/private-subnet-patient-management.pem \
          ubuntu@${{ secrets.SSH_HOST }}:/home/ubuntu/temp/

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 'bash -s' < backend/deploy.sh

    - name: Clean up temporary files
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} 'rm -rf /home/ubuntu/temp'